hello_human: "Hello human!"
thanks_human: "Thank you for reaching me!"
perfect: "Perfect!"
hello: "Hello!"
more: "Load more jobs"
thanks: "Thank you for authenticating your account human. Can I start hunting?"
letsgo: "Yes! Let's go"
nolater: "No, later"
alert: "Create an alert"
preferences: "Change preferences"
set_preferences: "Your preferences has been set to"
found: "I found a job matching your human preferences:"
sorry: "I'm sorry human, there are no more matches for:"
sorry_2: "Sorry human, I didn't understand that. You can use the messenger chat menu for more actions!"
menu_action: "You can change your preferences anytime using messenger chat menu or create an alert in order to receive new notifications if new results matching your research are posted."
menu_action_2: "You can change your preferences anytime using messenger chat menu."
change: "All good, let me know if you change your mind!"
job: "Are you looking for a job in Finland?"
job_choice: "Which job are you interested in?"
ye: "Yes"
ne: "No"
authenticate: "Authenticate your account first"
auth_action: "Authenticate"
changed_my_mind: "I changed my mind"
city_choice: "Which city would you like to work in?"
city_set: "Your city has been set to"
sad: "All right."
updated: "Keep me updated"
no_prefs: "it seems like you have not set your preferences yet"
reset: "Your preferences has been resetted, where would you like to work?"
contact: "I'm Paul from IcedCoffee team, you can contact me on gastongouron@gmail.com"
update: "Super! Gonna keep you updated when a new job matching your preferences is available!"
cool: "Cool!"
begin: "Let's begin!"
non_user: "Hello stranger!"