# hello_human: "Hello human!"
# thanks_human: "Thank you for reaching me!"
# perfect: "Perfect!"
# hello: "Hello!"
# more: "Load more jobs"
# thanks: "Thank you for authenticating your account human. Can I start hunting?"
# letsgo: "Yes! Let's go"
# nolater: "No, later"
# alert: "Create an alert"
# preferences: "Change preferences"
# set_preferences: "Your preferences has been set to"
# found: "I found a job matching your human preferences:"
# sorry: "I'm sorry human, there are no more matches for:"
# sorry_2: "Sorry human, I didn't understand that. You can use the messenger chat menu for more actions!"
# menu_action: "You can change your preferences anytime using messenger chat menu or create an alert in order to receive new notifications if new results matching your research are posted."
# menu_action_2: "You can change your preferences anytime using messenger chat menu."
# change: "All good, let me know if you change your mind!"
# job: "Are you looking for a job in Finland?"
# job_choice: "Which job are you interested in?"
# ye: "Yes"
# ne: "No"
# authenticate: "Authenticate your account first"
# auth_action: "Authenticate"
# changed_my_mind: "I changed my mind"
# city_choice: "Which city would you like to work in?"
# city_set: "Your city has been set to"
# sad: "All right."
# updated: "Keep me updated"
# no_prefs: "it seems like you have not set your preferences yet"
# reset: "Your preferences has been resetted, where would you like to work?"
# contact: "I'm Paul from IcedCoffee team, you can contact me on gastongouron@gmail.com"
# update: "Super! Gonna keep you updated when a new job matching your preferences is available!"
# cool: "Cool!"
# begin: "Let's begin!"
# non_user: "Hello stranger!"

hello_human: "Hei ihminen!"
thanks_human: "Kiitos, että tavoitit minut"
perfect: "Täydellistä!"
hello: "Hei!"
more: "Lataa lisää töitä"
thanks: "Kiitos tilin varmennuksesta ihminen! Voinko aloittaa etsinnän?"
letsgo: "Hienoa! Aloitetaan!"
nolater: "Ei, myöhemmin"
alert: "Luo hälytys"
preferences: "Muuta mieltymyksiäsi"
set_preferences: "Valintasi on laitettu"
found: "Löysin työn joka vastaa mieltymyksiäsi:"
sorry: "Olen pahoillani ihminen, en löytänyt enempää vastaavuuksia haullesi:"
sorry_2: "Anteeksi ihminen, en ymmärtänyt tuota. voit käyttää messengerin keskusteluvalikkoa löytääksesi lisää toimintoja!"
menu_action: "Voit vaihtaa mieltymyksiäsi koska tahansa käyttäen messengerin keskusteluvalikkoa, tai luoda uuden hälytyksen saadaksesni ilmoituksia jos löydän uuden tuloksen joka vastaa hakuasi"
menu_action_2: "Voit vaihtaa mieltymyksiäsi koska tahansa käyttäen messengerin keskusteluvalikkoa"
change: "Kaikki hyvin, kerro minulle jos muutat mielesi"
job: "Etsitkö töitä Suomesta?"
job_choice: "Mistä työstä olet kiinnostunut?"
ye: "Kyllä"
ne: "Ei"
authenticate: "Todenna tilisi ensin"
auth_action: "Todennettu"
changed_my_mind: "Muutin mieltäni"
city_choice: "Missä kaupungissa haluaisit tehdä töitä?"
city_set: "Kaupungiksesi on asetettu"
sad: "Asia selvä"
updated: "Pidä minut ajan tasalla"
no_prefs: "Vaikuttaa siltä, että et vielä ole asettanut mieltymyksiäsi"
reset: "Mieltymyksesi on nollattu, missä haluaisit työskennellä?"
contact: "Minä olen Paul, IcedCoffee tiimistä, voit ottaa minuun yhteyttä osoitteessa gastongouron@gmail.com"
update: "Kaikki kunnossa, pidän sinut ajan tasalla kun uusi työ joka vastaa mieltymyksiäsi löytyy"
cool: "Mahtvaa!"
begin: "Aloitetaan!"
non_user: "Hei muukalainen!"